SET NAMES UTF8;
DROP DATABASE IF EXISTS wg;
CREATE DATABASE wg CHARSET=UTF8;
USE wg;
CREATE TABLE wg_login(
	id INT PRIMARY KEY AUTO_INCREMENT,
	utext VARCHAR(25),
	upass VARCHAR(32)
);
INSERT INTO wg_login VALUES(null,521314,md5('abc123'));
INSERT INTO wg_login VALUES(null,2096131327,md5('xb1223'));

CREATE TABLE wg_recom(
	
);